# Generated by Django 3.1.2 on 2020-10-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableJobs',
            new_name='AvailableJob',
        ),
    ]
